backup scripts

diff --git a/linux-scripts/script-dependencies/template b/linux-scripts/script-dependencies/template
--- a/linux-scripts/script-dependencies/template
+++ b/linux-scripts/script-dependencies/template
@@ -8,8 +8,8 @@
 # Month. Year
 
 if [ "$(id -u)" != "0" ]; then
-        printf "${error}ERROR: The script must be run with sudo privileges!${reset}\n"
-        exit 1
+    printf "${error}ERROR: The script must be run with sudo privileges!${reset}\n"
+    exit 1
 fi
 
 printf "${info}Starting <fill in> script${reset}\n"
